### ISSUE TITLE
效果不好呀，是不是放错模型了？

### ISSUE THREAD

**Issue by LeiGitHub1024** [yu-li/AGLLNet#3]
我跑了一下，效果很差呀，全是白块。
效果比MBLLEN差太多了。

**Comment by yu-li** [comment]
> 我跑了一下，效果很差呀，全是白块。
> 效果比MBLLEN差太多了。

你可以提供下测试图片吗？

**Comment by ymmshi** [comment]
![image](https://user-images.githubusercontent.com/13198991/133786461-be7321be-244c-40ee-9726-b94dcc40266b.png)

示例图片的结果是这样子的

**Comment by ymmshi** [comment]
![image](https://user-images.githubusercontent.com/13198991/133789556-c7191a6b-a168-4184-b9bb-c1929477c85f.png)

测试一些图片，对于亮度极低的区域artifacts太明显了，处理的不好，但是对于亮度不是很低的图片比之前的方法要好。

**Comment by LeiGitHub1024** [comment]
这是我测试的

[](url
![1](https://user-images.githubusercontent.com/61541201/134308376-49ed03b9-f7c8-4740-95db-f09b94c16093.jpg)
![1](https://user-images.githubusercontent.com/61541201/134308404-746cdd08-dd7c-415c-b799-aa150b5841c9.png)
)

**Comment by yu-li** [comment]
> 这是我测试的
> 
> [](url
> ![1](https://user-images.githubusercontent.com/61541201/134308376-49ed03b9-f7c8-4740-95db-f09b94c16093.jpg)
> ![1](https://user-images.githubusercontent.com/61541201/134308404-746cdd08-dd7c-415c-b799-aa150b5841c9.png)
> )

这个我感觉是你输入的问题，压缩的比较重？我自己gamma curve一下你这个图片都会有块出现。你试过这个输入MBLLEN没有这个问题？
