### ISSUE TITLE
请问你的环境确实是 tf1.6 keras2.2.0 吗

### ISSUE THREAD

**Issue by woaiwojia4816294** [yu-li/AGLLNet#6]
请问你的环境确实是 tf1.6 keras2.2.0 吗？因为我报错 ValueError: bad marshal data (unknown type code)

**Comment by woaiwojia4816294** [comment]
请问您能用高版本的python重新训练一个模型发布吗

**Comment by yu-li** [comment]
> 请问你的环境确实是 tf1.6 keras2.2.0 吗？因为我报错 ValueError: bad marshal data (unknown type code)

是的 确认过环境没问题

**Comment by yu-li** [comment]
> 请问您能用高版本的python重新训练一个模型发布吗

不好意思 目前在忙其他项目了
